[tool.poetry]
name = "meta"
version = "0.0.1"
description = ""
authors = ["Meltano Team"]

[tool.poetry.dependencies]
python = "^3.9"
"ruamel.yaml" = "^0.17.28"
pytablewriter = "^0.64.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
