# A common CI workflow to run linting as defined in tox.ini
#
# Assumptions:
#
# 1. The repo has a tox.ini file, which defines a 'lint' command.
# 2. The lint operation will be run on the below-named python version.

name: Python Lint Checks from Tox (MeltanoLabs)

on: [push]

jobs:
  linting:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        # Only lint using the primary version used for dev
        python-version: [3.10]

    steps:
    - uses: actions/checkout@v3
    - name: Install Poetry
      uses: snok/install-poetry@v1
      with:
        version: 1.3.2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'poetry'
    - name: Install dependencies
      run: |
        poetry install
    - name: Run lint command from tox.ini
      run: |
        poetry run tox -e lint
